version: "3.19"

services:
  app:
    build: 
      context: ./app
    container_name: app
    image: challenge-node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    networks:
      - challenge-node-network
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge-node-network

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - challenge-node-network

networks:
  challenge-node-network:
    driver: bridge
